databases:
  - name: FinTrack-psql
    databaseName: FinTrack-psql
    user: fintrack
    plan: free

services:
  - type: web
    name: FinTrack
    runtime: ruby
    plan: free
    buildCommand: "bundle install && rails db:migrate"
    startCommand: "rails s -p 3000 -e development -b 0.0.0.0"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: FinTrack-psql
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
      - key: PORT
        value: 3000 # sensible default
      - key: VITE_API_URL
        value: https://fintrack-nygf.onrender.com

  - type: static_site
    name: FinTrack-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://fintrack-nygf.onrender.com
